### ISSUE TITLE
Mobile navigation is broken on docs.automotivelinux.org

### ISSUE THREAD

**Issue by glunardi** [automotive-grade-linux/docs-webtemplate#4]
The table of content for the docs are generated by 
- toc_recursive_main.html for the desktop view 
- toc_recursive_dropdown.html for the mobile view

There has been a few fixes upstream apparently related to this (a long while ago). Anyway, I have no way to test this but looks like the generated html is wrong (nothing to do with css or else).

**Comment by glunardi** [comment]
One difference I spotted between the two files that might make a difference is included in this file:

[toc_recursive_dropdown-agl-proposed-change.txt](https://github.com/automotive-grade-linux/docs-webtemplate/files/3069852/toc_recursive_dropdown-agl-proposed-change.txt)

**Comment by glunardi** [comment]
maybe the better option would be to rebase on the newer version of https://github.com/apache/cordova-docs where a similar patch seems to have been applied (before it was uploaded to github).

**Comment by sebd71** [comment]
Yes you're right. The pull request #5 you submit fixes the problem of menu in mobile navigation. I just merged the #5.
Unfortunately, I'm not sure we can easily rebase current version of AGL docs that diverged for codova-docs. Should be investigated...
